RISK_SCORE_THRESHOLDS = {
    "HIGH_RISK": 28,
    "MEDIUM_RISK": 18,
}

FUTURE_FAILURE_THRESHOLDS = {
    "HIGH_RISK_SCORE": 30,
    "MEDIUM_RISK_SCORE": 18,
    "LOW_SIGNAL_RISK_SCORE": 15,
    "BOOKING_FAILURE_RATE": 0.08,
    "PROCESS_ERROR_RATE": 0.15,
    "SEARCH_FAILURE_RATE": 0.25,
    "SEARCH_TIMEOUT_RATE": 0.18,
    "WALLET_RISK_SCORE": 12,
    "CREDIT_REJECTION_RATE": 0.15,
}

WARNING_THRESHOLDS = {
    "CRITICAL": 0.70,
    "WARNING": 0.45,
    "WATCH": 0.25,
}