RISK_SCORE_THRESHOLDS = {
    "HIGH_RISK": 28,
    "MEDIUM_RISK": 18,
}

RISK_SCORE_WEIGHTS = {
    "B_FAILURE_RATE": 20,
    "B_PENDING_RATE": 10,
    "B_CANCELLATION_RATE": 10,
    "B_DEADLINE_MISS_RATE": 8,
    "BP_ERROR_RATE": 12,
    "BP_STUCK_RATE": 8,
    "BP_HIGH_RETRY_RATE": 8,
    "BOOKING_NOT_ISSUED_RATE": 6,
    "SUPPLIER_PNR_MISSING_RATE": 5,
    "TICKET_NUMBER_MISSING_RATE": 5,
    "SUPPLIER_TICKETING_RISK_SCORE": 0.08,
    "REFUND_RISK_SCORE": 0.08,
    "CREDIT_RISK_SCORE": 0.08,
    "SESSION_RISK_SCORE": 0.08,
    "WALLET_RISK_SCORE": 0.08,
}

FUTURE_FAILURE_THRESHOLDS = {
    "HIGH_RISK_SCORE": 30,
    "MEDIUM_RISK_SCORE": 18,
    "LOW_SIGNAL_RISK_SCORE": 15,
    "BOOKING_FAILURE_RATE": 0.08,
    "PROCESS_ERROR_RATE": 0.15,
    "SEARCH_FAILURE_RATE": 0.25,
    "SEARCH_TIMEOUT_RATE": 0.18,
    "WALLET_RISK_SCORE": 12,
    "CREDIT_REJECTION_RATE": 0.15,
}

WARNING_THRESHOLDS = {
    "CRITICAL": 0.70,
    "WARNING": 0.45,
    "WATCH": 0.25,
}

MODEL_VERSION_CONFIG = {
    "MAX_MODEL_VERSIONS": 5,
}

ANOMALY_CONFIG = {
    "N_ESTIMATORS": 300,
    "CONTAMINATION": 0.20,
    "RANDOM_STATE": 42,
}

CLASSIFIER_CONFIG = {
    "RANDOM_STATE": 42,
    "N_ESTIMATORS": 300,
    "TEST_SIZE": 0.30,
}

FEATURE_WEIGHTS = {
    "failure_rate": 0.18,
    "pending_rate": 0.10,
    "process_error_rate": 0.16,
    "refund_rate": 0.10,
    "credit_rejection_rate": 0.10,
    "search_failure_rate": 0.20,
    "wallet_risk_rate": 0.16,
}